# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Shristi-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
   build-and-deploy:
    runs-on: ubuntu-latest
     # runs-on: ubuntu-latest
    # needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with: 
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shristi-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      

     
